### ISSUE TITLE
Remove broken `MLLP.Receiver.start/0`

### ISSUE THREAD

**Issue by bryanhunter** [HCA-Healthcare/elixir-mllp#25] opened 2021-11-24 19:10 UTC
At one point `MLLP.Receiver.start/0` could be called, and it would use the DefaultDispatcher. Currently, it only returns an error.

```
iex> MLLP.Receiver.start()                                           
** (ArgumentError) No tcp port provided
    (elixir_mllp 0.5.0) lib/mllp/receiver.ex:168: MLLP.Receiver.to_args/1
    (elixir_mllp 0.5.0) lib/mllp/receiver.ex:64: MLLP.Receiver.start/1
```

**Comment by vikas15bhardwaj** [comment] 2021-11-24 19:27
Port and dispatcher are required fields now, otherwise, it will raise error. Any idea, in which case we need to start without dispatcher.

**Comment by starbelly** [comment] 2021-11-29 17:17
@vikas15bhardwaj The issue is that we have `start(opts \\ [])` which  defines`start/0` which will of course result  in an error. We simply need to make opts mandatory. I'll open a PR to fix this up.

**Comment by starbelly** [comment] 2021-12-14 22:54
This was closed via #28

**Closed as completed** 2021-12-15 20:06 UTC
